# Input file for the CoronaPMCMC model

########### SIMULATION DETAILS #############

# Perform a simulation.
mode      = "sim"

# The time period of simulation (in weeks).
period    = 16

# The random seed used to run the simulation.
seed      = 0

# The output directory
outputdir	= "Output"

########### THE MODEL #############

# Defines the compartments in the model.
# Format: 'inf' gives the relative infectivity, 'dist' gives the distribution for waiting time.
# Here 'exp' stands for exponential and 'lognorm' stands for lognormal follow by any parameters which define these distributions.

comps			= [{name = "S", inf=0.0, dist="infection"},
						 {name = "E", inf=0.0, dist="lognorm", mean="muE", sd="sdE"},
						 {name = "A", inf=0.5, dist="exp", mean="tA"},
						 {name = "R", inf=0.0},
						 {name = "P", inf=0.5, dist="exp", mean="tP"},
						 {name = "I", inf=1.0, dist="exp", mean="tI"},
						 {name = "H", inf=0.0, dist="exp", mean="tH"},
						 {name = "D", inf=0.0}]

						 
# Defines transitions between compartments.
# Format: 'from' gives the initial compartment, 'to' gives the final compartment and 'prob' defines a branching probability.
# Note when a compartmental model has transitions to two others, only the probability down one branch needs to be defined.

trans   	=	[{from="S", to="E"},
						 {from="E", to="A", prob="probA"},
						 {from="E", to="P"},
						 {from="A", to="R"},
						 {from="P", to="I"},
						 {from="I", to="H", prob="probH"},
						 {from="I", to="R"},
						 {from="H", to="D", prob="probD"},
						 {from="H", to="R"}]
	
	
# Defines the parameters in the model

params		= [{name="beta0", value=3.0},         # The values for the beta spline
						 {name="beta1", value=3.0},
						 {name="beta2", value=2.5},
						 {name="beta3", value=0.7},
						 {name="beta4", value=0.8},
						 {name="phi", value=5.0},           # The values for the phi spline
						 {name="muE", value=1.63},          # The latent period
						 {name="sdE", value=0.5},			      # The standard deviation in latent period			 
						 {name="tA", value=8.0},            # Mean time spend in asymptomatic state
						 {name="tP", value=2.0},            # Mean time spend in pre-symptomatic state
						 {name="tI", value=2.0},            # Mean time spend in infectious state
						 {name="tH", value=20.0},           # Mean time spend in hospital
						 {name="probA", value=0.25},        # Probability of being asymptomatic
						 {name="probH", value=0.3},         # Probability of going to hospital given in the I state
						 {name="probD", value=0.3},         # Probability of death
						 {name="sus_adult", value=0.05},    # Relative susceptibility of adults (on log scale)
						 {name="sus_elderly", value=0.01},  # Relative susceptibility of elderly (on log scale)
						 {name="sus_male", value=0.02}]     # Relative susceptibility of males (on log scale)

						 
# Defines the linear spline used to represent disease transmission parameter beta.
# Format: The name of the parameter followed by the time of the spline point.

betaspline= [{param="beta0", time=0.0}, 
						 {param="beta1", time=4.0},
						 {param="beta2", time=8.0}, 
						 {param="beta3", time=12.0},
						 {param="beta4", time=16.0}]
						 

# Defines the linear spline used to represent external force of infection phi.
# Format: The name of the parameter followed by the time of the spline point. Note, The parameter 'zero' sets the value to zero.

phispline= [{param="phi", time=0.0}, 
						{param="phi", time=4.0},
						{param="zero", time=8.0}, 
						{param="zero", time=12.0},
						{param="zero", time=16.0}]
	

# The age groups used in the analysis.
# Format: The age range followed by a parameter giving the relative susceptibility (on the log scale). 
# Note, one parameter is set to 'zero' and the other parameters give the susceptibity relative to that group.

ages			= [{range="0-18", sus="zero"},{range="19-64", sus="sus_adult"},{range="65+", sus="sus_elderly"}]


# Other demographic categories
# Format: The name of the category is given followed by the potential values it can take along with their relative susceptibilities.

democats	= [[{value="Male", sus="sus_male"}, {value="Female", sus="zero"}] ]


########### THE DATA #############

# The data directory

#datadir		= "Data_ScotlandMSOA"
datadir		= "Data_example"

# A table giving data regions (e.g. "Lanarkshire	S08000032").
# Format: Tab-separated with region name then region code.

regions		= "regiondata.txt"


# A table giving information about areas.
# Format tab-separated table with: Area code, geographical position (long,lat), region code, columns for covariates (e.g. density of population), columns for populations in different age groups, columns for other deomgraphic categories (giving percentages).

areas			= "areadata.txt"


# A table informing the matrix of contacts between different areas 
# Note, this matrix is sparse hence only non-zero elelments are given.
# Format tab-separated table with: area A, area B and the mixing between areas A and B. 
# Note, the numbers for the areas correspond to where they appear in the 'areas' list above.  

geocont	 	= "Mdata.txt"


# A matrix giving the contact rates between different age groups.

agecont	 	= "Ndata.txt"
 
 
# The observed numbers of transitions between different compartments.
# Format: 'from' comapartment, 'to' compartment, the area used by the data ('reg'=on a regional level, 'all'=across all regions), the name of the file and the units used.

transdata	= [{from="I", to="H", area="reg", file="cases.txt", units="weeks"},
						 {from="H", to="D", area="all", file="deaths.txt", units="weeks"}]
